ESevaiTracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("iniyathalaimurai.urls")),
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

iniyathalaimurai/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "iniyathalaimurai"
urlpatterns = [
    # customer
    path('dashboard/', views.user_dashboard, name="user_dashboard"),
    path('applications/', views.user_applications, name="user_applications"),
    path('payments/', views.user_payments, name="user_payments"),
    path('applications/new/', views.new_application, name='new_application'),

    # staff
    path('staff/dashboard/', views.staff_dashboard, name="staff_dashboard"),

    path('customers/new/', views.new_customer, name='new_customer'),
    path('customers/manage/', views.manage_customers, name='manage_customers'),
    path('customers/manage/edit/<int:user_id>/', views.edit_customer, name='edit_customer'),
    path('customers/manage/delete/<int:user_id>/', views.delete_customer, name='delete_customer'),
    path('customers/manage/activate/<int:user_id>/', views.activate_customer, name='activate_customer'),
    path('customers/manage/deactivate/<int:user_id>/', views.deactivate_customer, name='deactivate_customer'),

    path('payments/manage/', views.manage_payments, name='manage_payments'),
    path('payments/<int:payment_id>/update-status/', views.update_payment_status, name='update_payment_status'),

    path('applications/manage/', views.manage_applications, name='manage_applications'),
    path('applications/<int:app_id>/upload-certificate/', views.upload_certificate, name='upload_certificate'),
    path('applications/<int:app_id>/update-status/', views.update_application_status, name='update_application_status'),
    path('applications/<int:app_id>/update-acknowledgement/', views.update_acknowledgement, name='update_acknowledgement'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import login_view, logout_view, signup_view

app_name = "users"
urlpatterns = [
    path('login/', login_view, name="login"),
    path('signup/', signup_view, name="signup"),
    path('logout/', logout_view, name="logout"),
]

iniyathalaimurai/models.py
from django.db import models
from users.models import User
from django.core.exceptions import ValidationError


def validate_filetype(value):
    valid_mimetypes = ['image/jpeg', 'image/png', 'application/pdf', 'image/webp']
    if value.content_type not in valid_mimetypes:
        raise ValidationError('Only JPG, PNG, and PDF files are allowed.')


class ServiceCategory(models.Model):
    name = models.CharField(max_length=100, unique=True) # Aadhaar, PAN, VoterId, Driving Licence, Ration Card
    image = models.FileField(upload_to='service_images/', blank=True, null=True)

    def __str__(self):
        return self.name

class Service(models.Model):
    category = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE, related_name='services')
    name = models.CharField(max_length=100)  # e.g. "enrolment", "update - name"
    price = models.DecimalField(max_digits=6, decimal_places=2, default=50.0)

    def __str__(self):
        return f"{self.category.name} - {self.name}"

class Application(models.Model):
    STATUS_CHOICES = [
        ('processing', 'Processing'),
        ('accepted', 'Accepted'),
        ('rejected', 'Rejected'),
    ]

    acknowledgementNumber = models.CharField(max_length=40, unique=True, blank=True, null=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applications')
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='processing')
    payment = models.OneToOneField('Payment', on_delete=models.SET_NULL, null=True, blank=True)
    userAppliedAt = models.DateTimeField(auto_now_add=True)
    applicationAppliedAt = models.DateTimeField(null=True, blank=True)
    certificate = models.FileField(
        upload_to='certificates/',
        blank=True,
        null=True
    )

    def __str__(self):
        if self.acknowledgementNumber:
            return f"{self.customer.phone_num}'s Application {self.acknowledgementNumber} - {self.service}"
        else:
            return f"{self.customer.phone_num}'s Application - {self.service}"


class Payment(models.Model):
    STATUS_CHOICES = [
        ('verifying', 'Verifying'),
        ('accepted', 'Accepted'),
        ('rejected', 'Rejected')
    ]

    transactionID = models.CharField(max_length=50, unique=True, blank=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='payments')
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='verifying')
    paidAt = models.DateTimeField(auto_now_add=True)
    screenshot = models.FileField(
        upload_to='payment_screenshots/',
        blank=True,
        null=True,
        validators=[validate_filetype]
    )

    def __str__(self):
        return f"{self.customer.phone_num}'s Payment {self.id} for {self.service} - {self.status}"

class SubmittedDocument(models.Model):
    application = models.ForeignKey('Application', on_delete=models.CASCADE, related_name='documents')
    file = models.FileField(upload_to='submitted_documents/', validators=[validate_filetype])

    def __str__(self):
        return f"Document for Application #{self.application.pk}"

iniyathalaimurai/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Application, ServiceCategory, Service, Payment, SubmittedDocument
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import date
from django.contrib import messages
from django.db import IntegrityError
from users.models import User
from django.views.decorators.http import require_POST
from django.db.models import Sum

@login_required(login_url='/users/login/')
def new_application(request):
    categories = ServiceCategory.objects.prefetch_related('services')
    preselected_cat_id = request.GET.get('category', 1)
    preselected_category = ServiceCategory.objects.get(id=preselected_cat_id)
    if request.method == 'POST':
        try:
            category_id = request.POST.get('category')
            service_id = request.POST.get('service')
            transaction_id = request.POST.get('transactionID')
            screenshot = request.FILES.get('paymentScreenshot')
            docs = request.FILES.getlist('docs')

            service = Service.objects.get(id=service_id)

            if Payment.objects.filter(transactionID=transaction_id).exists():
                messages.error(request, "This UPI Transaction ID has already been used. Application not submitted.")
                return redirect('iniyathalaimurai:new_application')

            payment = Payment.objects.create(
                transactionID=transaction_id,
                customer=request.user,
                service=service,
                amount=service.price,
                status='verifying',
                screenshot=screenshot
            )

            application = Application.objects.create(
                customer=request.user,
                service=service,
                status='processing',
                payment=payment
            )

            for doc in docs:
                SubmittedDocument.objects.create(application=application, file=doc)

            messages.success(request, f"Application for {application.service} is submitted successfully.")
            return redirect('iniyathalaimurai:new_application')

        except IntegrityError as e:
            print("IntegrityError during application/payment creation:", e)
            messages.error(request, "Something went wrong while submitting your application. Please try again.")

        except Exception as e:
            print("Unexpected error:", e)
            messages.error(request, "An unexpected error occurred. Please try again or contact support.")

    return render(request, 'iniyathalaimurai/new_application.html', {
        'categories': categories,
        'preselected_cat_id': preselected_cat_id,
        'preselected_category': preselected_category,
    })

@login_required(login_url="/users/login/")
def user_applications(request):
    categories = ServiceCategory.objects.prefetch_related('services')

    applications = Application.objects.filter(
        customer=request.user
    ).select_related('service', 'service__category').order_by('-userAppliedAt')

    paginator = Paginator(applications, 10)
    page_number = request.GET.get('page')

    try:
        page_obj = paginator.page(page_number)
    except (PageNotAnInteger, EmptyPage):
        page_obj = paginator.page(1)

    return render(request, 'iniyathalaimurai/my_applications.html', {
        'page_obj': page_obj,
        'categories': categories,
    })

@login_required(login_url="/users/login/")
def user_payments(request):
    categories = ServiceCategory.objects.prefetch_related('services')

    payments = Payment.objects.filter(
        customer=request.user
    ).select_related('service', 'service__category').order_by('-paidAt')

    paginator = Paginator(payments, 10)
    page_number = request.GET.get('page')

    try:
        page_obj = paginator.page(page_number)
    except (PageNotAnInteger, EmptyPage):
        page_obj = paginator.page(1)

    return render(request, 'iniyathalaimurai/my_payments.html', {
        'page_obj': page_obj,
        'categories': categories,
    })

@login_required(login_url="/users/login/")
def user_dashboard(request):
    user = request.user

    service_data = []
    
    categories = ServiceCategory.objects.prefetch_related('services')

    for category in categories:
        services = category.services.all()
        
        user_applications = Application.objects.filter(
            customer=user,
            service__in=services
        )
        application_count = user_applications.count()

        service_data.append({
            'id': category.id,
            'category': category.name,
            'image_url': category.image.url,
            'application_count': application_count
        })

    recent_applications = Application.objects.filter(customer=user).select_related('service', 'service__category').order_by('-userAppliedAt')[:10]

    context = {
        'service_data': service_data,
        'recent_applications': recent_applications,
        'categories': categories,
    }
    return render(request, 'iniyathalaimurai/user_dashboard.html', context)

@login_required(login_url="/users/login/")
def new_customer(request):
    if request.method == 'POST':
        phone_num = request.POST.get('phone_num')
        password = request.POST.get('password')
        name = request.POST.get('name')

        if User.objects.filter(phone_num=phone_num).exists():
            messages.error(request, 'Phone number already registered.')
        else:
            user = User.objects.create_user(phone_num=phone_num, name=name, password=password)
            user.is_staff = False
            user.save()
            messages.success(request, f'{user.phone_num} account created successfully!')
            return redirect('iniyathalaimurai:new_customer')
    return render(request, 'iniyathalaimurai/new_customer.html')


@login_required(login_url="/users/login/")
def manage_customers(request):
    customers_list = User.objects.filter(is_staff=False).order_by('-id')

    paginator = Paginator(customers_list, 10) 
    page_number = request.GET.get('page')

    try:
        page_obj = paginator.page(page_number)
    except (PageNotAnInteger, EmptyPage):
        page_obj = paginator.page(1)

    return render(request, 'iniyathalaimurai/customers.html', {
        'page_obj': page_obj,
    })

@login_required(login_url="/users/login/")
def delete_customer(request, user_id):
    customer = get_object_or_404(User, id=user_id)
    customer.delete()
    messages.success(request, f"Customer '{customer.phone_num}' deleted successfully.")
    return redirect('iniyathalaimurai:manage_customers')

@login_required(login_url="/users/login/")
def deactivate_customer(request, user_id):
    customer = get_object_or_404(User, id=user_id)
    if customer.is_active:
        customer.is_active = False
        customer.save()
        messages.success(request, f"Customer '{customer.phone_num}' deactivated.")
    return redirect('iniyathalaimurai:manage_customers')

@login_required(login_url="/users/login/")
def activate_customer(request, user_id):
    customer = get_object_or_404(User, id=user_id)
    if not customer.is_active:
        customer.is_active = True
        customer.save()
        messages.success(request, f"Customer '{customer.phone_num}' activated.")
    return redirect('iniyathalaimurai:manage_customers')


@login_required(login_url="/users/login/")
def edit_customer(request, user_id):
    customer = get_object_or_404(User, id=user_id)

    if request.method == 'POST':
        phone_num = request.POST.get('phone_num')
        name = request.POST.get('name')
        status = request.POST.get('status')

        updated = False
        if phone_num and phone_num != customer.phone_num:
            customer.phone_num = phone_num
            updated = True

        if name and name != customer.name:
            customer.name = name
            updated = True

        if status in ['active', 'inactive']:
            new_status = True if status == 'active' else False
            if customer.is_active != new_status:
                customer.is_active = new_status
                updated = True

        if updated:
            customer.save()
            messages.success(request, f'Customer {customer.phone_num} updated successfully!')
        else:
            messages.info(request, f'No changes made for {customer.phone_num}')

        return redirect('iniyathalaimurai:manage_customers')

    return render(request, 'iniyathalaimurai/edit_customer.html', {
        'customer': customer
    })

@login_required(login_url='/users/login/')
def manage_payments(request):
    payments_list = Payment.objects.select_related('customer', 'service', 'service__category').order_by('-paidAt')

    paginator = Paginator(payments_list, 10)
    page_number = request.GET.get('page')

    try:
        page_obj = paginator.page(page_number)
    except (PageNotAnInteger, EmptyPage):
        page_obj = paginator.page(1)

    return render(request, 'iniyathalaimurai/manage_payments.html', {
        'page_obj': page_obj
    })

@require_POST
@login_required(login_url='/users/login/')
def update_payment_status(request, payment_id):
    payment = get_object_or_404(Payment, id=payment_id)
    new_status = request.POST.get('status')

    if new_status in dict(Payment.STATUS_CHOICES):
        payment.status = new_status
        payment.save()
        messages.success(request, f'Payment #{payment.transactionID} status updated to {new_status}.')
    else:
        messages.error(request, 'Invalid status.')

    return redirect('iniyathalaimurai:manage_payments')

@login_required(login_url='/users/login/')
def manage_applications(request):
    applications = Application.objects.select_related('customer', 'service', 'service__category').order_by('-userAppliedAt')

    paginator = Paginator(applications, 10)
    page_number = request.GET.get('page')

iniyathalaimurai/templates/partials/navbar.html
{% load static %}
<nav class="navbar bg-base-100 w-full max-sm:rounded max-sm:shadow-sm sm:border-b border-base-content/25 z-10 h-16 sticky top-0">
    <button type="button" class="btn btn-text max-sm:btn-square sm:hidden me-2" aria-haspopup="dialog" aria-expanded="false" aria-controls="with-navbar-sidebar" data-overlay="#with-navbar-sidebar" >
        <span class="icon-[tabler--menu-2] size-5"></span>
    </button>
    <div class="navbar-start flex flex-1 items-center">
        <a class="link text-base-content link-neutral text-xl font-bold no-underline flex items-center gap-2" href="#">
            <img src="{% static 'iniyathalaimurai/esevai logo.png' %}" alt="esevai logo" class="size-8">
            <p>Iniya Thalaimurai</p>
        </a>
    </div>
    <div class="navbar-end flex items-center gap-4">
        <div class="dropdown relative inline-flex [--auto-close:inside] [--offset:8] [--placement:bottom-end]">
        <button id="dropdown-scrollable" type="button" class="dropdown-toggle flex items-center" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown">
            <div class="avatar">
                <div class="size-9.5 rounded-full mx-2">
                    <img src="{% static 'iniyathalaimurai/pfp.png' %}" alt="user avatar" />
                </div>
            </div>
            <div class="sm:flex items-center flex-col justify-center hidden">
                <p class="text-base-content">
                    {% if request.user.name %}
                        {{ request.user.name }}
                    {% else %}
                        {{ request.user.phone_num }}
                    {% endif %}
                </p>
                <small class="text-base-content/50">
                    {% if request.user.is_staff %}
                        Admin
                    {% else %}
                        Customer
                    {% endif %}
                </small>
            </div>
        </button>
        <ul class="dropdown-menu dropdown-open:opacity-100 shadow-md border border-base-content/25 hidden min-w-60" role="menu" aria-orientation="vertical" aria-labelledby="dropdown-avatar">
            <li class="dropdown-header justify-center items-start gap-2">
                <div class="flex  flex-col items-start px-2">
                    <p class="text-base-content sm:hidden">
                    {% if request.user.name %}
                        {{ request.user.name }}
                    {% else %}
                        {{ request.user.phone_num }}
                    {% endif %}
                    </p>
                    <p class="text-base-content text-sm">{{ request.user.phone_num }}</p>
                </div>
                <p class="text-base-content/50 text-sm px-2 sm:hidden">
                    {% if request.user.is_staff %}
                        Admin
                    {% else %}
                        Customer
                    {% endif %}
                </p>
            </li>
            <li>
            <a class="dropdown-item" href="#" class="hover:text-bg-soft-primary">
                <span class="icon-[tabler--user]"></span>
                My Profile
            </a>
            </li>
            <li>
            <a class="dropdown-item" href="#" class="hover:text-bg-soft-primary">
                <span class="icon-[tabler--settings]"></span>
                Settings
            </a>
            </li>
            <li>
            <a class="dropdown-item" href="#" class="hover:text-bg-soft-primary">
                <span class="icon-[tabler--receipt-rupee]"></span>
                Billing
            </a>
            </li>
            <li>
            <a class="dropdown-item" href="#" class="hover:text-bg-soft-primary">
                <span class="icon-[tabler--help-triangle]"></span>
                FAQs
            </a>
            </li>
            <li class="dropdown-footer gap-2">
            <a class="btn btn-error btn-soft btn-block" href="{% url 'users:logout' %}">
                <span class="icon-[tabler--logout]"></span>
                Sign out
            </a>
            </li>
        </ul>
        </div>
    </div>
</nav>

iniyathalaimurai/templates/partials/sidebar.html
{% load static %}
{% with path=request.path selected_category_id=request.GET.category %}
<aside id="with-navbar-sidebar" class="w-72 bg-base-100 sm:h-[calc(100vh-4rem)] sm:sticky sm:top-[4rem] hidden sm:flex flex-col overlay [--auto-close:sm] sm:shadow-none overlay-open:translate-x-0 drawer sm:pt-0 pt-4 drawer-start sm:translate-x-0 sm:border-r border-base-content/25" role="dialog" tabindex="-1" >
    <div class="hidden">
        <span class="icon-[tabler--letter-a]"></span>
        <span class="icon-[tabler--letter-p]"></span>
        <span class="icon-[tabler--letter-d]"></span>
        <span class="icon-[tabler--letter-r]"></span>
        <span class="icon-[tabler--letter-v]"></span>
    </div>
    <div class="drawer-body px-2 py-2">
        <ul class="menu space-y-0.5 p-0">
            <li>
                <a href="{% url 'iniyathalaimurai:user_dashboard' %}" class="{% if path == '/dashboard/' %} text-bg-soft-primary {% endif %} hover:text-bg-soft-primary">
                    <span class="icon-[tabler--home] size-5"></span>
                    Dashboard
                </a>
            </li>
            <li class="space-y-0.5">
                {% with new_appln_url=path|slice:":18" %}
                <a class="collapse-toggle hover:text-bg-soft-primary" id="menu-app" data-collapse="#menu-app-collapse">
                    <span class="icon-[tabler--apps] size-5"></span>
                    New Application
                    <span class="icon-[tabler--chevron-down] collapse-open:rotate-180 size-4 transition-all duration-300"></span>
                </a>
                <ul id="menu-app-collapse" class="collapse {% if new_appln_url == '/applications/new/' %}collapse-open{% else %}hidden{% endif %} w-auto space-y-0.5 overflow-hidden transition-[height] duration-300" aria-labelledby="menu-app">
                    {% for cat in categories %}
                    <li>
                        <a href="{% url 'iniyathalaimurai:new_application' %}?category={{ cat.id }}" 
                        class="{% if cat.id|stringformat:'s' == selected_category_id %}text-bg-soft-primary{% endif %} hover:text-bg-soft-primary">
                            {% with initial=cat.name|slice:":1" %}
                            <span class="icon-[tabler--letter-{{ initial|lower }}] size-5"></span>
                            {% endwith %}
                            {{ cat.name }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
                {% endwith %}
            </li>
            <div class="divider text-base-content/50 m-0 py-6">View</div>
            <li>
                <a href="{% url 'iniyathalaimurai:user_applications' %}" class="{% if path == '/applications/' %} text-bg-soft-primary {% endif %} hover:text-bg-soft-primary">
                <span class="icon-[tabler--file-check] size-5"></span>
                    My Applications
                </a>
            </li>
            <li>
                <a href="{% url 'iniyathalaimurai:user_payments' %}" class="{% if path == '/payments/' %} text-bg-soft-primary {% endif %} hover:text-bg-soft-primary">
                <span class="icon-[tabler--currency-rupee] size-5"></span>
                    My Payments
                </a>
            </li>
            <div class="divider text-base-content/50 m-0 py-6">Account</div>
            <li>
                <a href="#" class="hover:text-bg-soft-primary">
                <span class="icon-[tabler--user] size-5"></span>
                    My Profile
                </a>
            </li>
        </ul>
    </div>
</aside>
{% endwith %}

iniyathalaimurai/templates/partials/staff sidebar.html
{% load static %}
{% load custom_filters %}
{% with path=request.path %}
<aside id="with-navbar-sidebar" class="w-72 bg-base-100 sm:h-[calc(100vh-4rem)] sm:sticky sm:top-[4rem] hidden sm:flex flex-col overlay [--auto-close:sm] sm:shadow-none overlay-open:translate-x-0 drawer sm:pt-0 pt-4 drawer-start sm:translate-x-0 sm:border-r border-base-content/25" role="dialog" tabindex="-1" >
    <div class="hidden">
        <span class="icon-[tabler--letter-a]"></span>
        <span class="icon-[tabler--letter-p]"></span>
        <span class="icon-[tabler--letter-d]"></span>
        <span class="icon-[tabler--letter-r]"></span>
        <span class="icon-[tabler--letter-v]"></span>
    </div>
    <div class="drawer-body px-2 py-2">
        <ul class="menu space-y-1 p-0">
            <li>
                <a href="{% url 'iniyathalaimurai:staff_dashboard' %}" class="{% if path == '/staff/dashboard/' %} text-bg-soft-primary {% endif %} hover:text-bg-soft-primary">
                    <span class="icon-[tabler--home] size-5"></span>
                    Dashboard
                </a>
            </li>
            <li class="space-y-1">
                <a class="collapse-toggle hover:text-bg-soft-primary" id="menu-app" data-collapse="#menu-app-collapse">
                    <span class="icon-[tabler--user-cog] size-5"></span>
                    User Management
                    <span class="icon-[tabler--chevron-down] collapse-open:rotate-180 size-4 transition-all duration-300"></span>
                </a>
                <ul id="menu-app-collapse" class="collapse {% if path|startswith:'/customers/' %}collapse-open{% else %}hidden{% endif %} w-auto space-y-0.5 overflow-hidden transition-[height] duration-300" aria-labelledby="menu-app" >
                    <li>
                        <a href="{% url 'iniyathalaimurai:new_customer' %}" class="{% if path == '/customers/new/' %}text-bg-soft-primary{% endif %} hover:text-bg-soft-primary">
                        <span class="icon-[tabler--user-plus] size-5"></span>
                            New Customer
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'iniyathalaimurai:manage_customers' %}" class="{% if path|startswith:'/customers/manage/' %}text-bg-soft-primary{% endif %} hover:text-bg-soft-primary">
                        <span class="icon-[tabler--user-edit] size-5"></span>
                            Manage Customers
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="{% url 'iniyathalaimurai:manage_applications' %}" class="{% if path == '/applications/manage/' %} text-bg-soft-primary {% endif %} hover:text-bg-soft-primary">
                <span class="icon-[tabler--file-check] size-5"></span>
                    Manage Applications
                </a>
            </li>
            <li>
                <a href="{% url 'iniyathalaimurai:manage_payments' %}" class="{% if path == '/payments/manage/' %} text-bg-soft-primary {% endif %} hover:text-bg-soft-primary">
                    <span class="icon-[tabler--receipt-rupee-filled] size-5"></span>
                    Manage Payments
                </a>
            </li>
            <div class="divider text-base-content/50 m-0 py-6">Account</div>
            <li>
                <a href="#" class="hover:text-bg-soft-primary">
                <span class="icon-[tabler--user] size-5"></span>
                    My Profile
                </a>
            </li>
        </ul>
    </div>
</aside>
{% endwith %}